<%@ Page Language="C#" MasterPageFile="~/Masterbase.master" AutoEventWireup="true"
    CodeFile="shoppinglist.aspx.cs" Inherits="shoppinglist" Title="Untitled Page" %>

<%@ Import Namespace="System.Data" %>
<%@ Import Namespace="System.Data.SqlClient" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">

    <script runat="server">

    
        DataTable dt = new DataTable();
 
        protected void Page_Load(object sender, EventArgs e)
        {

           // int init_table = Convert.ToInt32(Request.QueryString["sclk"]);
            //if (!IsPostBack )
            //{
                initialtable();
           //}
            if (Session["Tables"] != null )
            {
                sessiondataorplus();
            }

        }
        void sessiondataorplus()
        {
            dt = (DataTable)(Session["Tables"]);

            GV.DataSource = dt;
            GV.DataBind();

        }

        void initialtable()
        {

            DataColumn idColumn = new DataColumn(" ", Type.GetType("System.Int32"));
            idColumn.AutoIncrement = true;
            DataColumn itemsColumn = new DataColumn("items", Type.GetType("System.String"));
            DataColumn qtyColumn = new DataColumn("quantity", Type.GetType("System.Int32"));
            DataColumn priceColumn = new DataColumn("Price", Type.GetType("System.Decimal"));

            dt.Columns.Add(idColumn);
            dt.Columns.Add(itemsColumn);
            dt.Columns.Add(qtyColumn);
            dt.Columns.Add(priceColumn);

            DataRow dr;

            for (int i = 0; i <= 10; i++)
            {
                dr = dt.NewRow();
                dr["items"] = "LCD TV" + i;
                dr["quantity"] = 1;
                dr["Price"] = 433478.00;

                dt.Rows.Add(dr);
            }

            //dt.AcceptChanges();
            GV.DataSource = dt;
            
            GV.DataBind();


        }

        //void btnback_Click(object sender, EventArgs e)
        //{

        //    Session["Tables"] = dt;
            
        //}

        protected void GV_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {


            // dt.RowDeleting += new DataRowChangeEventHandler(Row_Deleting);
            DataRowCollection itemColumns = dt.Rows;

            itemColumns[e.RowIndex].Delete();
            dt.AcceptChanges();
            GV.DataSource = dt;
            GV.DataBind();
        }
        protected void GV_RowDataBound(object sender, GridViewRowEventArgs e)
        {

            e.Row.Cells[0].Width = Unit.Pixel(5);
           // e.Row.Cells[1].Visible = false;
            e.Row.Cells[0].BorderColor = System.Drawing.Color.Black;

            e.Row.Cells[0].BackColor = System.Drawing.Color.FromArgb(242, 242, 242);

            if (e.Row.RowType == DataControlRowType.DataRow)
            {

                for (int i = 2; i < e.Row.Cells.Count; i++)
                {

                    TextBox txt = new TextBox();
                    txt.Text = e.Row.Cells[i].Text;
                    if (txt.Text == "&nbsp;")
                    {
                        txt.Text = "";
                    }

                    txt.TextMode = TextBoxMode.SingleLine;

                    txt.Rows = 1;

                    //txt.CssClass = "textBox";

                    txt.BorderWidth = Unit.Pixel(0);

                    txt.Width = Unit.Pixel(180);

                    //txt.Text = "";

                    e.Row.Cells[i].Controls.Add(txt);

                    e.Row.Cells[i].BorderColor = System.Drawing.Color.Black;

                    txt.Attributes.Add("onclick", "javascript:setFocus(this)");

                }
                //LinkButton btn = new LinkButton();
                //btn.Text = "Delete";
                //btn.ID = "btn";

                //e.Row.Cells[5].Controls.Add(btn);


            }
            else if (e.Row.RowType == DataControlRowType.Header)
            {

                e.Row.BackColor = System.Drawing.Color.FromArgb(242, 242, 242);

                for (int i = 1; i < e.Row.Cells.Count; i++)
                {

                    e.Row.Cells[i].BorderColor = System.Drawing.Color.Black;

                }

            }


        }

    </script>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    
        <asp:GridView ID="GV" runat="server" OnRowDataBound="GV_RowDataBound" OnRowDeleting="GV_RowDeleting"
            AutoGenerateDeleteButton="true">
        </asp:GridView>
       <%-- <asp:Button ID="btnback" runat="server" Text="Save and Continue Shopping" OnClick="btnback_Click" PostBackUrl="~/shoppinglist.aspx?sclk=1"  />
        <asp:Button ID="btnNext" runat="server" Text="Next" />--%>
   
</asp:Content>
